server {
    listen 80;
    server_name _;

    # Frontend (React/Vite)
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Seguridad básica
    location ~ /\.ht {
        deny all;
    }
}
